INSERT INTO Series (title, author_id, subgenre_id) VALUES ("Series One",1,1);
INSERT INTO Series (title, author_id, subgenre_id) VALUES ("Series Two",2,2);
INSERT INTO subgenres (name) VALUES ("space opera");
INSERT INTO subgenres (name) VALUES ("romantic comedy");
INSERT INTO authors (name) VALUES ("J.K. Rowling");
INSERT INTO authors (name) VALUES ("J.R.R. Tolkein");
INSERT INTO books (title, year, series_id) VALUES ("Book One",2000,1);
INSERT INTO books (title, year, series_id) VALUES ("Book Two",2001,1);
INSERT INTO books (title, year, series_id) VALUES ("Book Three",2002,1);
INSERT INTO books (title, year, series_id) VALUES ("Book One",2000,2);
INSERT INTO books (title, year, series_id) VALUES ("Book Two",2001,2);
INSERT INTO books (title, year, series_id) VALUES ("Book Three",2002,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Sam","The One And Only","human",1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Romeo","Love after","human",1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Juliet","Love before","human",1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Frodo","The ring of power","hobbit",1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Bilbo","Also the ring of power","hobbit",2,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Gandalf","staff","human",2,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Harry Potter","the chosen one","human",2,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Dumbledore","also staff","human",2,2);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (2,1);
INSERT INTO character_books (book_id, character_id) VALUES (3,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,2);
INSERT INTO character_books (book_id, character_id) VALUES (2,2);
INSERT INTO character_books (book_id, character_id) VALUES (3,2);
INSERT INTO character_books (book_id, character_id) VALUES (1,3);
INSERT INTO character_books (book_id, character_id) VALUES (2,4);
INSERT INTO character_books (book_id, character_id) VALUES (4,5);
INSERT INTO character_books (book_id, character_id) VALUES (5,5);
INSERT INTO character_books (book_id, character_id) VALUES (6,5);
INSERT INTO character_books (book_id, character_id) VALUES (4,6);
INSERT INTO character_books (book_id, character_id) VALUES (5,6);
INSERT INTO character_books (book_id, character_id) VALUES (6,6);
INSERT INTO character_books (book_id, character_id) VALUES (4,7);
INSERT INTO character_books (book_id, character_id) VALUES (5,8);
